#!/usr/bin/env python3
"""Generate branding/dicti-panel-states.svg.

Three authentic GNOME top-bar strips stacked vertically (idle / listening /
transcribing), animated with SMIL so they play on GitHub when embedded via
<img>. Motion mirrors gnome-extension/dicti@local/extension.js:
  IDLE        static trapezoid [0.5,1,1,1,0.5], deep green
  LISTENING   organic equalizer bounce, pink
  PROCESSING  left->right fill sweep, deep green
Throwaway generator (see memory: brand SVGs are regenerated by a script).
"""

GREEN = "#3c9a5e"
PINK = "#e85ba6"
PANEL = "#1c1c1e"      # near-black GNOME panel
CLOCK = "#f2f2f2"

# layout
SVG_W = 748
LABEL_R = 112          # right edge for the left-hand state labels
STRIP_X = 132
STRIP_W = 600
STRIP_H = 36
R = 9
TOP = 18
ROW_GAP = 28

# bars
N = 5
BAR_W = 3.4
BAR_GAP = 2.6
MAXH = 15.0
RAD = BAR_W / 2
GROUP_W = N * BAR_W + (N - 1) * BAR_GAP

KS = "0.42 0 0.58 1"   # ease-in-out per segment (calcMode=spline)

# organic listening waveforms (height fractions) + per-bar duration
LISTEN = [
    ([0.42, 0.70, 0.50, 0.82, 0.40, 0.62, 0.46], 1.06),
    ([0.60, 0.92, 0.54, 0.74, 0.50, 0.86, 0.60], 0.92),
    ([0.50, 0.64, 0.88, 0.46, 0.72, 0.52, 0.50], 1.18),
    ([0.72, 0.50, 0.90, 0.58, 0.80, 0.46, 0.72], 0.84),
    ([0.40, 0.60, 0.46, 0.70, 0.50, 0.56, 0.42], 1.00),
]

# processing fill waveform (matches fillHeight: rise / hold / fall)
FILL_VALS = [0.18, 1.0, 1.0, 0.18]
FILL_TIMES = [0.0, 0.28, 0.82, 1.0]
FILL_DUR = 1.7
FILL_STAGGER = 0.16


def keytimes(n):
    return ";".join(f"{i/(n-1):.4f}" for i in range(n))


def splines(n):
    return ";".join([KS] * (n - 1))


def row_center(row):
    return TOP + row * (STRIP_H + ROW_GAP) + STRIP_H / 2


def bars_x():
    # bars sit right of the centered clock, like the real panel. The offset
    # leaves margin for wider fallback fonts (Cantarell is absent on mobile /
    # GitHub, so the clock renders wider) so the bars never touch the text.
    return STRIP_X + STRIP_W / 2 + 96


def bar_x(i):
    return bars_x() + i * (BAR_W + BAR_GAP)


def static_bar(x, base_y, frac, color):
    h = max(RAD * 1.4, frac * MAXH)
    y = base_y - h
    return (f'<rect x="{x:.2f}" y="{y:.2f}" width="{BAR_W}" height="{h:.2f}" '
            f'rx="{RAD}" fill="{color}"/>')


def anim_bar(x, base_y, fracs, times_str, splines_str, dur, begin, color,
            pose=None):
    # `pose` sets the static authored height (the frame shown by renderers
    # that ignore SMIL, e.g. GitHub's social preview); animation still drives
    # motion in-browser. Defaults to the first keyframe.
    hs = [max(RAD * 1.4, f * MAXH) for f in fracs]
    ys = [base_y - h for h in hs]
    pf = fracs[0] if pose is None else pose
    h0 = max(RAD * 1.4, pf * MAXH)
    y0 = base_y - h0
    hvals = ";".join(f"{h:.2f}" for h in hs)
    yvals = ";".join(f"{y:.2f}" for y in ys)
    b = f' begin="{begin:.2f}s"' if begin else ""
    common = (f'calcMode="spline" keyTimes="{times_str}" '
              f'keySplines="{splines_str}" dur="{dur}s" '
              f'repeatCount="indefinite"{b}')
    return (
        f'<rect x="{x:.2f}" y="{y0:.2f}" width="{BAR_W}" height="{h0:.2f}" '
        f'rx="{RAD}" fill="{color}">'
        f'<animate attributeName="height" values="{hvals}" {common}/>'
        f'<animate attributeName="y" values="{yvals}" {common}/>'
        f'</rect>')


def strip_bg(row):
    y = TOP + row * (STRIP_H + ROW_GAP)
    return (f'<rect x="{STRIP_X}" y="{y}" width="{STRIP_W}" height="{STRIP_H}" '
            f'rx="{R}" fill="{PANEL}"/>')


def clock(row):
    cy = row_center(row) + 5
    cx = STRIP_X + STRIP_W / 2
    return (f'<text x="{cx:.0f}" y="{cy:.1f}" text-anchor="middle" '
            f'font-family="Cantarell, \'Segoe UI\', system-ui, sans-serif" '
            f'font-size="14.5" font-weight="600" fill="{CLOCK}" '
            f'opacity="0.92">Thu 18 Jun&#160;&#160;16:37</text>')


def label(row, text, color):
    cy = row_center(row) + 4.5
    return (f'<text x="{LABEL_R}" y="{cy:.1f}" text-anchor="end" '
            f'font-family="\'JetBrains Mono\', ui-monospace, SFMono-Regular, '
            f'Menlo, monospace" font-size="13" font-weight="600" '
            f'fill="{color}">{text}</text>')


def build():
    h = TOP + 3 * STRIP_H + 2 * ROW_GAP + TOP
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{SVG_W}" '
        f'height="{h}" viewBox="0 0 {SVG_W} {h}" '
        f'font-family="sans-serif" role="img" '
        f'aria-label="dicti panel indicator in three states: idle, listening, '
        f'transcribing">',
    ]

    # row 0: IDLE, static green trapezoid
    out.append(strip_bg(0))
    out.append(clock(0))
    out.append(label(0, "idle", "#8a8a8e"))
    base0 = row_center(0) + MAXH / 2
    for i, f in enumerate([0.5, 1.0, 1.0, 1.0, 0.5]):
        out.append(static_bar(bar_x(i), base0, f, GREEN))

    # row 1: LISTENING, pink equalizer
    out.append(strip_bg(1))
    out.append(clock(1))
    out.append(label(1, "listening", PINK))
    base1 = row_center(1) + MAXH / 2
    for i, (fracs, dur) in enumerate(LISTEN):
        kt = keytimes(len(fracs))
        ks = splines(len(fracs))
        out.append(anim_bar(bar_x(i), base1, fracs, kt, ks, dur, 0, PINK))

    # row 2: PROCESSING, green fill sweep
    out.append(strip_bg(2))
    out.append(clock(2))
    out.append(label(2, "transcribing", GREEN))
    base2 = row_center(2) + MAXH / 2
    kt = ";".join(f"{t:.4f}" for t in FILL_TIMES)
    ks = splines(len(FILL_VALS))
    pose = [1.0, 0.9, 0.7, 0.45, 0.28]   # mid-sweep look for static fallback
    for i in range(N):
        begin = -((N - 1 - i) * FILL_STAGGER)
        out.append(anim_bar(bar_x(i), base2, FILL_VALS, kt, ks,
                            FILL_DUR, begin, GREEN, pose=pose[i]))

    out.append("</svg>")
    return "\n".join(out)


if __name__ == "__main__":
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "dicti-panel-states.svg")
    with open(path, "w") as fh:
        fh.write(build() + "\n")
    print("wrote", path)
